language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - "pip install -r src/requirements.txt"
  - "pip install -r src/requirements_test.txt"
script:
  - "coverage run src/tests/runUnitTests.py"
  - "coverage xml -o coverage.xml"
after_success:
  - "coveralls"
