version: '3.7'

services:

  app:
    build: .
    networks:
      - helpradar
    depends_on:
      - postgresql
    volumes:
      - ./src:/usr/helpradar
    environment:
      DB_HOST: postgresql
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: postgres

  postgresql:
    image: postgres:12.2-alpine
    networks:
      - helpradar
    volumes:
      - postgresql:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: secret

volumes:
  postgresql: {}

networks:
  helpradar:
    driver: bridge