version: '3.7'

services:

  app:
    build: .
    network_mode: bridge
    links:
      - postgresql
    volumes:
      - ./src:/usr/helpradar
    environment:
      DB_HOST: postgresql
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: postgres

  postgresql:
    image: postgres:12.2-alpine
    network_mode: bridge
    volumes:
      - postgresql:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: secret

volumes:
  postgresql: {}
